import { aiRegistry } from '../../server/ai/provider.js';
import { convertFileToMarkdown } from '../../server/document-markdown.js';

export const config = { api: { bodyParser: { sizeLimit: '50mb' } } };
const COUNT_SCHEMA = { type: 'OBJECT', properties: { questionCount: { type: 'INTEGER' }, lastQuestionNumber: { type: 'INTEGER' } }, required: ['questionCount', 'lastQuestionNumber'] };
type CountResult = { questionCount: number; lastQuestionNumber: number };
type InlineFile = { mimeType: string; data: string; name?: string; textPreview?: string };
const stripDataUrl = (v: string) => String(v || '').replace(/^data:[^;]+;base64,/, '');
const normalizeText = (v: string) => String(v || '').replace(/\r/g, '\n').replace(/[\u00a0\u2000-\u200b]/g, ' ').replace(/\uFEFF/g, '').replace(/\n{3,}/g, '\n\n');
const validCount = (count: number, last: number): CountResult | null => Number.isInteger(count) && count >= 1 && count <= 1000 && Number.isInteger(last) && last >= 1 && last <= 1000 ? { questionCount: count, lastQuestionNumber: last } : null;
function extractJson(text: string): any { const s = String(text || '').replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim(); try { return JSON.parse(s); } catch {} const a = s.indexOf('{'), b = s.lastIndexOf('}'); if (a >= 0 && b > a) { try { return JSON.parse(s.slice(a, b + 1)); } catch {} } throw new Error('JARVIS could not read the source question count.'); }
function parseCountText(text: string): CountResult | null { const s = normalizeText(text); const j = s.match(/\{[\s\S]{0,500}?"questionCount"\s*:\s*(\d{1,4})[\s\S]{0,300}?"lastQuestionNumber"\s*:\s*(\d{1,4})[\s\S]{0,100}?\}/i); if (j) { const r = validCount(Number(j[1]), Number(j[2])); if (r) return r; } const r = s.match(/(?:Q(?:uestion)?\s*\.?\s*)?(\d{1,4})\s*(?:to|through|–|—|-)\s*(\d{1,4})\s*(?:questions?|प्रश्न)?/i); if (r && Number(r[1]) === 1) { const n = validCount(Number(r[2]), Number(r[2])); if (n) return n; } const c = s.match(/(?:question\s*count|total\s*(?:number\s*of\s*)?questions?|number\s*of\s*questions?)\s*[:=\-]?\s*(\d{1,4})/i); const l = s.match(/(?:last\s*question(?:\s*number)?|final\s*question(?:\s*number)?|last\s*(?:printed\s*)?number)\s*[:=\-]?\s*(\d{1,4})/i); return validCount(c ? Number(c[1]) : 0, l ? Number(l[1]) : c ? Number(c[1]) : 0); }
function detectCountFromQuestionSequence(text: string): CountResult | null { const s = normalizeText(text), nums = new Set<number>(); for (const re of [/\bQ(?:uestion)?\s*\.?\s*(\d{1,4})\s*[.)\-:]?/gi, /\bQuestion\s*(?:No\.?\s*)?(\d{1,4})\s*[.)\-:]?/gi, /(?:^|\s)(\d{1,4})\s*[.)\-:]\s+/gm]) { let m: RegExpExecArray | null; while ((m = re.exec(s)) !== null) { const n = Number(m[1]); if (Number.isInteger(n) && n >= 1 && n <= 1000) nums.add(n); } } if (!nums.has(1)) return null; let last = 0; for (let n = 1; n <= 1000; n++) { if (!nums.has(n)) break; last = n; } return last ? { questionCount: last, lastQuestionNumber: last } : null; }
function detectCountFromSectionRanges(text: string): CountResult | null { const s = normalizeText(text), ranges: Array<{ start: number; end: number; count: number }> = []; const patterns = [/(?:\(|\[)?\s*(\d{1,3})\s*(?:to|-)\s*(\d{1,3})\s*(?:\)|\])?\s*(?:[\u2013\u2014-]\s*)?(?:This section contains|Section contains)\s*(\d{1,3})\s*questions/gi, /(?:This section contains|Section contains)\s*(\d{1,3})\s*questions[\s\S]{0,120}?(?:\(|\[)?\s*(\d{1,3})\s*(?:to|-)\s*(\d{1,3})/gi]; for (const re of patterns) { let m: RegExpExecArray | null; while ((m = re.exec(s)) !== null) { const a = Number(m[1]), b = Number(m[2]), c = Number(m[3]); const start = re === patterns[0] ? a : b, end = re === patterns[0] ? b : c, count = re === patterns[0] ? c : a; if (start >= 1 && end >= start && count === end - start + 1) ranges.push({ start, end, count }); } } if (!ranges.length) return null; ranges.sort((a,b)=>a.start-b.start); let expected=1,last=0; for(const r of ranges){if(r.start!==expected)break;expected=r.end+1;last=r.end;} return last?{questionCount:last,lastQuestionNumber:last}:null; }
async function enrichForCount(files: any[]): Promise<InlineFile[]> { return Promise.all(files.map(async f => { const base: InlineFile = { mimeType:f.type||'application/pdf', data:stripDataUrl(f.base64Data||''), name:f.name, textPreview:typeof f.textPreview==='string'?f.textPreview:undefined }; if(base.textPreview?.trim()||!f.base64Data)return base; try{const md=await convertFileToMarkdown(f);if(md)return {...base,textPreview:md.slice(0,120000)};}catch(e){console.warn(`[MarkItDown] Source-count conversion failed for ${f.name}; using Gemini PDF input.`,e);} return base; })); }
async function askCountFromText(provider:any,text:string,model:string):Promise<CountResult|null>{if(!text.trim())return null;const body=text.length>180000?`${text.slice(0,90000)}\n\n[...middle omitted...]\n\n${text.slice(-90000)}`:text;try{const raw=await provider.generateText(`Determine the ACTUAL number of numbered questions in this source text. Ignore option numbers, page numbers, section numbers and marks. Find the real sequence beginning at Q1 and identify the final question number. Never assume 180. Return ONLY JSON: {"questionCount": number, "lastQuestionNumber": number}.\n\nSOURCE TEXT:\n${body}`,{model,responseMimeType:'application/json',responseSchema:COUNT_SCHEMA,inlineFiles:[],skipDocumentContext:true});try{const d=extractJson(raw),r=validCount(Number(d?.questionCount),Number(d?.lastQuestionNumber));if(r)return r;}catch{}return parseCountText(raw);}catch(e){console.warn('[Source Count] text-only Gemini count failed:',e);return null;}}
async function askCountFromVision(provider:any,files:InlineFile[],model:string):Promise<CountResult|null>{const pdfs=files.filter(f=>f.data&&f.mimeType.toLowerCase().includes('pdf'));if(!pdfs.length)return null;try{const raw=await provider.generateText('Inspect the attached original PDF visually. Determine the ACTUAL final printed question number and total number of real numbered questions. Ignore option labels, page numbers, section numbers and marks. Verify the sequence starts at Q1. Never assume 180. Return ONLY JSON: {"questionCount": number, "lastQuestionNumber": number}.',{model,responseMimeType:'application/json',responseSchema:COUNT_SCHEMA,inlineFiles:pdfs.map(f=>({mimeType:f.mimeType,data:f.data})),skipDocumentContext:true});try{const d=extractJson(raw),r=validCount(Number(d?.questionCount),Number(d?.lastQuestionNumber));if(r)return r;}catch{}return parseCountText(raw);}catch(e){console.error('[Source Count] visual Gemini count failed:',e);return null;}}
export default async function handler(req:any,res:any){if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({error:'Method not allowed'});}try{const files=Array.isArray(req.body?.attachedFiles)?req.body.attachedFiles:[];if(!files.length)return res.status(400).json({error:'No readable source file was attached.'});const inline=await enrichForCount(files);if(!inline.some(f=>f.data||f.textPreview?.trim()))return res.status(400).json({error:'The uploaded source contains neither readable text nor file bytes.'});const text=inline.map(f=>f.textPreview?.trim()||'').filter(Boolean).join('\n\n');const a=detectCountFromSectionRanges(text);if(a)return res.status(200).json({...a,detectionMethod:'document-text-structure'});const b=detectCountFromQuestionSequence(text);if(b)return res.status(200).json({...b,detectionMethod:'document-text-sequence'});const provider=aiRegistry.getProvider('gemini'),model=req.body?.model||'gemini-3.8-flash';const c=await askCountFromText(provider,text,model);if(c)return res.status(200).json({...c,detectionMethod:'gemini-text-fallback'});const d=await askCountFromVision(provider,inline,model);if(d)return res.status(200).json({...d,detectionMethod:'gemini-visual-fallback'});return res.status(422).json({error:'JARVIS could not verify the source question count after checking the document text and original PDF.',code:'SOURCE_COUNT_UNRESOLVED'});}catch(err:any){console.error('[Source Count Error]',err);return res.status(500).json({error:err?.message||'Failed to detect source question count.'});}}
