import { AlignmentType, BorderStyle, Document, ImageRun, Math as DocxMath, MathFraction, MathRadical, MathRun, MathSubScript, MathSuperScript, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from 'docx';
import sharp from 'sharp';

export interface DocxPaperData {
  title: string; instituteName?: string; className?: string; subject?: string; examType?: string; date?: string; duration?: string; totalMarks?: string | number; medium?: string; chapterName?: string; syllabus?: string; instructions?: string[]; includeAnswerKey?: boolean; includeSolutions?: boolean;
  questions?: Array<{ number: number|string; sectionName?: string; questionType?: 'mcq'|'numerical'|'unknown'; textEn: string; textHi?: string; optionsEn?: string[]; optionsHi?: string[]; correctOption?: string; solution?: string; diagramSvg?: string; sourcePage?: number }>;
  rawContent?: string;
}
const EN='Times New Roman', HI='Noto Sans Devanagari', SIZE=24;
const BORDER={style:BorderStyle.SINGLE,size:4,color:'CBD5E1'} as const;
const BORDERS={top:BORDER,bottom:BORDER,left:BORDER,right:BORDER};
const NONE={top:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},bottom:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},left:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},right:{style:BorderStyle.NONE,size:0,color:'FFFFFF'}};
function plain(s:string){return String(s||'').replace(/\[\[MATH:([\s\S]*?)\]\]/g,'$1').replace(/\\times/g,'×').replace(/\\cdot/g,'·').replace(/\\pm/g,'±').replace(/\\leq/g,'≤').replace(/\\geq/g,'≥').replace(/\\neq/g,'≠').replace(/\\propto/g,'∝').replace(/\\infty/g,'∞').replace(/\\rightarrow|\\to/g,'→').replace(/\\alpha/g,'α').replace(/\\beta/g,'β').replace(/\\gamma/g,'γ').replace(/\\delta/g,'δ').replace(/\\theta/g,'θ').replace(/\\lambda/g,'λ').replace(/\\mu/g,'μ').replace(/\\pi/g,'π').replace(/\\rho/g,'ρ').replace(/\\sigma/g,'σ').replace(/\\phi/g,'φ').replace(/\\omega/g,'ω').replace(/\\sqrt\{([^{}]+)\}/g,'√($1)').trim();}
function group(s:string,i:number){if(s[i]!=='{')return null;let d=0;for(let j=i;j<s.length;j++){if(s[j]==='{')d++;if(s[j]==='}')if(!--d)return{value:s.slice(i+1,j),next:j+1};}return null;}
function mathParts(s:string):any[]{const out:any[]=[];let b='';const flush=()=>{if(b){out.push(new MathRun(plain(b)));b='';}};for(let i=0;i<s.length;){if(s.startsWith('\\frac',i)){flush();let j=i+5;while(/\s/.test(s[j]||''))j++;const a=group(s,j);if(a){j=a.next;while(/\s/.test(s[j]||''))j++;const c=group(s,j);if(c){out.push(new MathFraction({numerator:mathParts(a.value),denominator:mathParts(c.value)}));i=c.next;continue;}}}if(s.startsWith('\\sqrt',i)){flush();let j=i+5;while(/\s/.test(s[j]||''))j++;const a=group(s,j);if(a){out.push(new MathRadical({children:mathParts(a.value)}));i=a.next;continue;}}if(s[i]==='^'||s[i]==='_'){const sup=s[i]==='^';let j=i+1,v='';if(s[j]==='{'){const a=group(s,j);if(a){v=a.value;j=a.next;}}else{v=s[j]||'';j++;}if(v&&out.length){const base=out.pop();out.push(sup?new MathSuperScript({children:[base],superScript:mathParts(v)}):new MathSubScript({children:[base],subScript:mathParts(v)}));i=j;continue;}}const g=s.slice(i).match(/^\\(alpha|beta|gamma|delta|theta|lambda|mu|pi|rho|sigma|phi|omega)\b/);if(g){flush();const m:Record<string,string>={alpha:'α',beta:'β',gamma:'γ',delta:'δ',theta:'θ',lambda:'λ',mu:'μ',pi:'π',rho:'ρ',sigma:'σ',phi:'φ',omega:'ω'};out.push(new MathRun(m[g[1]]));i+=g[0].length;continue;}b+=s[i++];}flush();return out.length?out:[new MathRun('')];}
function rich(s:string,hindi=false,bold=false):any[]{const out:any[]=[];const re=/\[\[MATH:([\s\S]*?)\]\]/g;let last=0,m:RegExpExecArray|null;while((m=re.exec(s))){if(m.index>last)out.push(new TextRun({text:plain(s.slice(last,m.index)),font:hindi?HI:EN,size:SIZE,bold}));out.push(new DocxMath({children:mathParts(m[1])}));last=m.index+m[0].length;}if(last<s.length)out.push(new TextRun({text:plain(s.slice(last)),font:hindi?HI:EN,size:SIZE,bold}));return out.length?out:[new TextRun({text:plain(s),font:hindi?HI:EN,size:SIZE,bold})];}
function p(s:string,hindi=false,bold=false){return new Paragraph({spacing:{after:35,line:285},children:rich(s,hindi,bold)});}
function cell(children:any[],width:number){return new TableCell({width:{size:width,type:WidthType.PERCENTAGE},borders:BORDERS,margins:{top:80,bottom:80,left:100,right:100},children});}
function placeholderSvg(q:any){const graph=/graph|plot|axis|curve/i.test(`${q.textEn} ${q.textHi||''}`);const label=graph?'GRAPH / PLOT REQUIRED':'FIGURE / DIAGRAM REQUIRED';const page=q.sourcePage?`SOURCE PAGE ${q.sourcePage}`:'SOURCE PAGE —';return `<svg xmlns="http://www.w3.org/2000/svg" width="720" height="190"><rect x="2" y="2" width="716" height="186" rx="10" fill="#f8fafc" stroke="#64748b" stroke-width="3" stroke-dasharray="10 7"/><text x="360" y="68" text-anchor="middle" font-family="Arial" font-size="25" font-weight="700" fill="#0f172a">MANUAL ${label}</text><text x="360" y="108" text-anchor="middle" font-family="Arial" font-size="18" fill="#334155">Q.${String(q.number)} · Add the missing visual here</text><text x="360" y="143" text-anchor="middle" font-family="Arial" font-size="15" fill="#64748b">${page}</text></svg>`;}
async function image(svg:string){try{const data=await sharp(Buffer.from(svg,'utf8')).resize({width:540,withoutEnlargement:true}).png().toBuffer();return new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:45,after:55},children:[new ImageRun({type:'png',data,transformation:{width:540,height:143}})]});}catch{return null;}}
function options(values:string[],hindi=false){const rows:TableRow[]=[];for(let i=0;i<4;i+=2)rows.push(new TableRow({cantSplit:true,children:[cell([p(`(${i+1}) ${values[i]||''}`,hindi)],50),cell([p(`(${i+2}) ${values[i+1]||''}`,hindi)],50)]}));return new Table({width:{size:100,type:WidthType.PERCENTAGE},rows,borders:NONE});}
export async function generateDocxBuffer(data:DocxPaperData):Promise<Buffer>{const children:Array<Paragraph|Table>=[];children.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:35},children:[new TextRun({text:plain(data.instituteName||''),bold:true,size:30,font:EN})]}));children.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:65},children:[new TextRun({text:plain(data.title||'Bilingual Question Paper'),bold:true,size:25,font:EN})]}));children.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[cell([p(`Exam: ${data.examType||''}`)],25),cell([p(`Subject: ${data.subject||''}`)],25),cell([p(`Duration: ${data.duration||''}`)],25),cell([p(`Max Marks: ${data.totalMarks||''}`)],25)]})],borders:BORDERS}));for(const x of data.instructions||[])children.push(p(x));const qs=data.questions||[];if(qs.length){children.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:[cell([p('ENGLISH',false,true)],50),cell([p('हिन्दी',true,true)],50)]})],borders:BORDERS}));let section='';for(const q of qs){if(q.sectionName&&q.sectionName!==section){children.push(p(q.sectionName,false,true));section=q.sectionName;}const en:any[]=[p(`Q.${q.number}  ${q.textEn}`,false,true)];const hi:any[]=[p(q.textHi||'',true,true)];const visual=await image(q.diagramSvg?.trim()||placeholderSvg(q));if(visual){en.push(visual);const h=await image(q.diagramSvg?.trim()||placeholderSvg(q));if(h)hi.push(h);}if(q.questionType!=='numerical'){en.push(options(q.optionsEn||[]));hi.push(options(q.optionsHi||[],true));}children.push(new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({cantSplit:true,children:[cell(en,50),cell(hi,50)]})],borders:BORDERS}));}}else if(data.rawContent){for(const line of data.rawContent.split(/\r?\n/))if(line.trim())children.push(p(line));}const doc=new Document({creator:'JARVIS AI OFFICE',title:data.title||'Bilingual Question Paper',styles:{default:{document:{run:{font:{ascii:EN,hAnsi:EN,eastAsia:HI,cs:EN},size:SIZE}}}},sections:[{properties:{page:{margin:{top:520,bottom:520,left:650,right:650}}},children}]});return Packer.toBuffer(doc);}
