import { aiRegistry } from './ai/provider.js';
import { agentRegistry } from './agents/definitions.js';
import { memoryStore } from './memory.js';
import { generateDocxBuffer, DocxPaperData } from './docx-generator.js';
import { AttachedFile, ExecutionResult, GeneratedArtifact, TaskRecord, TaskStep, TaskStatus } from '../src/types/index.js';

export interface ExecuteTaskParams { userPrompt:string; selectedAgentId?:string; attachedFiles?:AttachedFile[]; model?:string; settings?:{instituteName?:string;targetExam?:string;defaultTargetExam?:string;primaryLanguage?:string;aiModel?:string}; onStep?:(step:TaskStep)=>void; }
const PAPER_SCHEMA={type:'OBJECT',properties:{title:{type:'STRING'},instituteName:{type:'STRING'},examType:{type:'STRING'},subject:{type:'STRING'},duration:{type:'STRING'},totalMarks:{type:'STRING'},instructions:{type:'ARRAY',items:{type:'STRING'}},questions:{type:'ARRAY',items:{type:'OBJECT',properties:{number:{type:'STRING'},textEn:{type:'STRING'},textHi:{type:'STRING'},options:{type:'ARRAY',items:{type:'OBJECT',properties:{en:{type:'STRING'},hi:{type:'STRING'}},required:['en','hi']}},correctOption:{type:'STRING'},solution:{type:'STRING'},diagramSvg:{type:'STRING'}},required:['number','textEn','textHi','options']}}},required:['title','questions']};
function isPaperAgent(id:string){return id==='neet-jee-paper'||id==='dpp-generator'||id==='pdf-bilingual';}
function sourceConversion(prompt:string,files?:AttachedFile[]){const p=prompt.toLowerCase();return !!files?.length&&/bilingual|translate|translation|convert|exact|same|faithful|preserve|hindi|अनुवाद|बाइलिंगुअल|जैसा है|सिर्फ/.test(p);}
function wantsKey(prompt:string){return /answer\s*key|उत्तर\s*कुंजी/i.test(prompt);}
function wantsSolutions(prompt:string){return /solution|solutions|step[- ]by[- ]step|विस्तृत हल|हल सहित/i.test(prompt);}
function extractJson(text:string):any{const cleaned=text.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'').trim();try{return JSON.parse(cleaned);}catch{}const a=cleaned.indexOf('{'),b=cleaned.lastIndexOf('}');if(a>=0&&b>a){try{return JSON.parse(cleaned.slice(a,b+1));}catch{}}throw new Error('JARVIS received invalid structured data and stopped before creating the Word file.');}
function countRequested(prompt:string):number|null{const m=prompt.match(/\b(\d{1,3})\s*(?:questions?|qs?|प्रश्न)\b/i);return m?Number(m[1]):null;}
function validate(data:DocxPaperData,prompt:string,sourceLocked:boolean){const qs=data.questions||[],expected=countRequested(prompt);if(expected!==null&&qs.length!==expected)throw new Error(`Question count mismatch: requested ${expected}, received ${qs.length}.`);const seen=new Set<string>();for(const q of qs){const n=String(q.number).replace(/^Q\.?(?:Q\.)?/i,'');if(seen.has(n))throw new Error(`Duplicate question Q.${n}.`);seen.add(n);if(!q.textEn?.trim()||!q.textHi?.trim())throw new Error(`Q.${n} is missing English or Hindi text.`);if(!q.optionsEn||q.optionsEn.length!==4||!q.optionsHi||q.optionsHi.length!==4)throw new Error(`Q.${n} must contain four English and four Hindi options.`);for(let i=0;i<4;i++)if(!q.optionsEn[i]?.trim()||!q.optionsHi[i]?.trim())throw new Error(`Q.${n} option ${String.fromCharCode(65+i)} is missing a language value.`);if(!sourceLocked&&(wantsKey(prompt)||wantsSolutions(prompt))&&!/^[A-D]$/i.test(String(q.correctOption||'')))throw new Error(`Q.${n} has no valid answer key.);}}

export class TaskRunner{
 static routeAgent(prompt:string,files?:AttachedFile[],manual?:string):string{
  if(manual&&manual!=='auto'){const a=agentRegistry.getAgent(manual);if(a?.enabled)return a.id;}
  const lower=prompt.toLowerCase();
  if(sourceConversion(prompt,files))return 'pdf-bilingual';
  const hasPdf=files?.some(f=>f.type.includes('pdf')||f.name.toLowerCase().endsWith('.pdf'));
  if(['notice','poster','circular','ptm','holiday','vacation','announcement','seminar'].some(k=>lower.includes(k)))return'poster-notice';
  if(['reel','short','video script','shot list','voiceover','60 second','30 second','video concept'].some(k=>lower.includes(k)))return'reel-content';
  if(['instagram','facebook','youtube community','caption','hashtag','carousel','social media','admission open','promo post'].some(k=>lower.includes(k)))return'social-media';
  if(['dpp','daily practice','practice problem','homework sheet','practice sheet'].some(k=>lower.includes(k)))return'dpp-generator';
  if(hasPdf||lower.includes('pdf')||(lower.includes('read')&&!!files?.length))return'pdf-bilingual';
  if(['neet','jee','question paper','test paper','exam paper','questions','physics','chemistry','biology','botany','zoology','maths','mathematics'].some(k=>lower.includes(k)))return'neet-jee-paper';
  const custom=agentRegistry.getAllAgents().find(a=>a.isCustom&&a.enabled&&lower.includes(a.name.toLowerCase()));if(custom)return custom.id;
  const words=prompt.trim().replace(/\s+/g,' ').split(' ').slice(0,6).join(' ');const existing=agentRegistry.getAllAgents().find(a=>a.isCustom&&a.enabled&&a.description.toLowerCase().includes(`auto-hired for: ${words.toLowerCase()}`));if(existing)return existing.id;
  return agentRegistry.addCustomAgent({name:`Specialist — ${words.slice(0,42)}`,description:`Auto-hired for: ${words}`,capabilities:['custom'],systemPrompt:`You are a JARVIS specialist created for this request: ${prompt}. Follow exact user requirements, preserve source content, do not invent missing facts, and return production-ready work.`,inputRequirements:['User instructions','Optional documents'],outputTypes:['markdown','docx'],category:'custom',enabled:true,iconName:'Bot',samplePrompts:[prompt]}).id;
 }
 static async execute(params:ExecuteTaskParams):Promise<TaskRecord>{
  const id=`task-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,start=Date.now(),steps:TaskStep[]=[];const add=(status:TaskStatus,label:string,details?:string)=>{const s={status,label,timestamp:new Date().toISOString(),details};steps.push(s);try{params.onStep?.(s);}catch{}};
  add('waiting','JARVIS command received');const locked=sourceConversion(params.userPrompt,params.attachedFiles);const agentId=this.routeAgent(params.userPrompt,params.attachedFiles,params.selectedAgentId),agent=agentRegistry.getAgent(agentId)||agentRegistry.getAgent('neet-jee-paper')!;
  add('understanding',agent.isCustom?`HR hired ${agent.name}`:`Intent understood · ${agent.name}`,agent.isCustom?'Specialist created for this request.':`Selected Agent ID: ${agent.id}`);add('working',locked?'SOURCE LOCK ACTIVE · uploaded document is authoritative':'Task parameters validated');
  const memory=memoryStore.getMemoryPromptContext(),configuredInstitute=params.settings?.instituteName||'',configuredExam=params.settings?.targetExam||params.settings?.defaultTargetExam||'',structured=isPaperAgent(agent.id);
  const lockRules=locked?`\n\nSOURCE-LOCK MODE — DOCUMENT CONVERSION ONLY:\n- The attached file is the sole source of truth.\n- Copy source header, institute, date, exam/class, subject, instructions, numbering, question text, options, tables, formulas, units, symbols and diagrams faithfully.\n- Do not add, remove, correct, rewrite, summarize, normalize, reorder, merge or improve source content.\n- Do not use JARVIS settings as replacements for source metadata.\n- Do not add answer keys, solutions, explanations, summaries or new headings unless they already exist in the source or the user explicitly requests them.\n- English source text stays unchanged. Translate only into Hindi. Every A-D option must have a Hindi translation.\n- Preserve source errors/ambiguities instead of silently fixing them.\n- Do not create per-question ENGLISH/HINDI headers; the renderer provides one bilingual header.\n- Creative generation is disabled for this task.`:'';
  const system=`${agent.systemPrompt}\n\n${memory}\n\nJARVIS PRODUCTION RULES:\n- Never invent, silently correct, merge, reorder or drop source content.\n- Preserve mathematical notation, units, superscripts, subscripts, Greek letters, fractions and scientific notation.\n- For bilingual output every question and every A-D option needs English and Hindi fields.\n- Creative generation is allowed only when the user explicitly asks to create new content.${lockRules}\n${structured?'\nReturn ONLY valid JSON matching the schema. No markdown fences or commentary.':''}`;
  add('generating',locked?'Translating source · no content creation':`Generating with ${params.model||'Gemini 3.7 Flash'}`);let raw='';try{const provider=aiRegistry.getProvider('gemini');const inline=(params.attachedFiles||[]).filter(f=>!!f.base64Data).map(f=>({mimeType:f.type||'application/pdf',data:(f.base64Data||'').replace(/^data:[^;]+;base64,/,'')}));raw=await provider.generateText(params.userPrompt,{systemInstruction:system,model:params.model||'gemini-3.7-flash',responseMimeType:structured?'application/json':undefined,responseSchema:structured?PAPER_SCHEMA:undefined,inlineFiles:inline.length?inline:undefined});}catch(e:any){add('failed',`Generation failed: ${e.message}`);return this.failed(id,start,params,agent,steps,e.message);}
  add('checking',locked?'Running source-fidelity + bilingual QA':'Running bilingual + structural QA');let data:DocxPaperData;try{data=structured?this.fromJson(extractJson(raw),params.userPrompt,configuredInstitute,configuredExam,locked):{title:params.userPrompt.slice(0,60),instituteName:configuredInstitute,examType:configuredExam,rawContent:raw};if(structured)validate(data,params.userPrompt,locked);}catch(e:any){add('failed',`QA failed: ${e.message}`);return this.failed(id,start,params,agent,steps,e.message);}
  const artifacts:GeneratedArtifact[]=[];try{const buf=await generateDocxBuffer(data);artifacts.push({id:`art-${Date.now()}-1`,name:`${agent.shortCode}_${Date.now()}.docx`,fileType:'docx',docxBase64:buf.toString('base64'),size:buf.length,metadata:{title:data.title,questionsCount:data.questions?.length||0}});}catch(e:any){add('failed',`DOCX generation failed: ${e.message}`);return this.failed(id,start,params,agent,steps,e.message);}artifacts.push({id:`art-${Date.now()}-2`,name:`${agent.shortCode}_content.${structured?'json':'md'}`,fileType:structured?'json':'markdown',content:structured?JSON.stringify(data,null,2):raw,size:Buffer.byteLength(structured?JSON.stringify(data):raw,'utf8')});add('completed',locked?'Source-faithful bilingual document ready':'Task completed successfully');const result:ExecutionResult={summary:`Successfully executed by ${agent.name}`,rawText:raw,structuredData:data,artifacts,agentUsed:{id:agent.id,name:agent.name},metrics:{durationMs:Date.now()-start}};return{id,title:params.userPrompt.slice(0,70),userPrompt:params.userPrompt,agentId:agent.id,agentName:agent.name,status:'completed',createdAt:new Date(start).toISOString(),completedAt:new Date().toISOString(),steps,attachedFiles:params.attachedFiles||[],result};
 }
 private static fromJson(data:any,prompt:string,configuredInstitute:string,configuredExam:string,locked:boolean):DocxPaperData{if(!data||!Array.isArray(data.questions))throw new Error('No questions array returned.');return{title:String(data.title||prompt.slice(0,60)),instituteName:String(data.instituteName||(!locked?configuredInstitute:'')),examType:String(data.examType||(!locked?configuredExam:'')),subject:String(data.subject||''),duration:String(data.duration||''),totalMarks:data.totalMarks??'',instructions:Array.isArray(data.instructions)?data.instructions:[],includeAnswerKey:!locked&&wantsKey(prompt),includeSolutions:!locked&&wantsSolutions(prompt),questions:data.questions.map((q:any,i:number)=>({number:String(q.number||i+1).replace(/^Q\.?(?:Q\.)?/i,''),textEn:String(q.textEn||'').trim(),textHi:String(q.textHi||'').trim(),optionsEn:Array.isArray(q.options)?q.options.map((o:any)=>String(o?.en||'').trim()):[],optionsHi:Array.isArray(q.options)?q.options.map((o:any)=>String(o?.hi||'').trim()):[],correctOption:String(q.correctOption||'').trim().toUpperCase(),solution:String(q.solution||'').trim(),diagramSvg:typeof q.diagramSvg==='string'&&q.diagramSvg.trim()?q.diagramSvg.trim():undefined}))};}
 private static failed(id:string,start:number,params:ExecuteTaskParams,agent:any,steps:TaskStep[],error:string):TaskRecord{return{id,title:params.userPrompt.slice(0,60),userPrompt:params.userPrompt,agentId:agent.id,agentName:agent.name,status:'failed',createdAt:new Date(start).toISOString(),completedAt:new Date().toISOString(),steps,attachedFiles:params.attachedFiles||[],error};}
}
