import React,{useEffect,useRef,useState}from'react';
import * as THREE from'three';
import {OrbitControls}from'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader}from'three/examples/jsm/loaders/GLTFLoader.js';
import * as SkeletonUtils from'three/examples/jsm/utils/SkeletonUtils.js';
import {RoundedBoxGeometry}from'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import {AgentDefinition,TaskRecord}from'../types';
interface Props{agents:AgentDefinition[];activeTask:TaskRecord|null}
type Actor={g:THREE.Group;model:THREE.Object3D;mixer:THREE.AnimationMixer;actions:Record<string,THREE.AnimationAction>;active?:THREE.AnimationAction;home:THREE.Vector3;phase:number;speed:number;visitor:boolean;state:'idle'|'walk'|'run'|'work'|'wait'};
const MODEL='https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/models/gltf/Xbot.glb';
const OfficeSimulation3DRealistic:React.FC<Props>=({agents,activeTask})=>{const host=useRef<HTMLDivElement>(null);const taskRef=useRef(activeTask);taskRef.current=activeTask;const[view,setView]=useState<'3d'|'top'>('3d');const[loading,setLoading]=useState(true);const[failed,setFailed]=useState(false);const viewRef=useRef(view);viewRef.current=view;
useEffect(()=>{const el=host.current;if(!el)return;let dead=false,raf=0;const scene=new THREE.Scene();scene.background=new THREE.Color(0x050a10);scene.fog=new THREE.Fog(0x050a10,28,72);const camera=new THREE.PerspectiveCamera(46,1,.1,100);camera.position.set(17,10,17);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;el.replaceChildren(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.enablePan=false;controls.minDistance=7;controls.maxDistance=38;controls.minPolarAngle=.35;controls.maxPolarAngle=1.43;controls.target.set(0,1,0);const root=new THREE.Group();scene.add(root);
const M=(c:number,r=.55,m=.05,e=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m,emissive:e,emissiveIntensity:e?1.2:0});const box=(s:[number,number,number],p:[number,number,number],m:THREE.Material,par:THREE.Object3D=root,r=.05)=>{const q=new THREE.Mesh(new RoundedBoxGeometry(...s,5,r),m);q.position.set(...p);q.castShadow=true;q.receiveShadow=true;par.add(q);return q};const cyl=(r:number,h:number,p:[number,number,number],m:THREE.Material,par:THREE.Object3D=root)=>{const q=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,20),m);q.position.set(...p);q.castShadow=true;q.receiveShadow=true;par.add(q);return q};
const floor=M(0x444b4e,.78,.08),wall=M(0x111d24,.75,.25),wood=M(0x6d4932,.4,.14),metal=M(0x151c21,.24,.8),screen=M(0x06252d,.16,.5,0x00a9c5),blue=M(0x1e6f93,.42,.12),glass=new THREE.MeshPhysicalMaterial({color:0x63dbe8,transparent:true,opacity:.1,roughness:.08,metalness:.15,transmission:.38,thickness:.05});
box([30,.5,20],[0,-.3,0],M(0x071017,.9,.25));box([29,.12,19],[0,.02,0],floor,root,.01);for(let x=-13;x<=13;x+=2)box([.012,.01,18],[x,.09,0],M(0x1d292e,.95));for(let z=-8;z<=8;z+=2)box([28,.01,.012],[0,.09,z],M(0x1d292e,.95));box([29,4,.4],[0,2,-9.35],wall);box([.4,4,18],[-14.8,2,0],wall);box([.4,4,18],[14.8,2,0],wall);for(const x of[-7,0,7])box([.08,3.3,7.4],[x,1.65,1.7],glass,root,.02);
scene.add(new THREE.HemisphereLight(0xdff8ff,0x071018,2.2));const sun=new THREE.DirectionalLight(0xffead3,4);sun.position.set(-10,18,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);for(const x of[-9,-3,3,9]){box([3,.08,.18],[x,5.2,0],M(0x1b252b,.22,.8),root,.03);const l=new THREE.PointLight(0xffd5a0,2.8,7);l.position.set(x,4.8,0);scene.add(l)}
const desks=[[-10,-5.6],[-3.4,-5.6],[3.4,-5.6],[10,-5.6],[-10,5.6],[-3.4,5.6],[3.4,5.6],[10,5.6]] as const;const obstacles:{x:number;z:number;w:number;d:number}[]=[];const desk=(x:number,z:number,rot=0)=>{const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rot;root.add(g);box([2.7,.18,1.25],[0,1.05,0],wood,g,.06);for(const sx of[-1,1])for(const sz of[-.42,.42])box([.07,.9,.07],[sx*1.08,.53,sz],metal,g,.02);box([1.55,.75,.07],[0,1.5,-.3],metal,g,.04);box([1.35,.58,.025],[0,1.5,-.34],screen,g,.015);box([.8,.04,.3],[.15,1.16,.25],M(0xe5e2d9,.55),g,.01);const chair=new THREE.Group();chair.position.z=.9;g.add(chair);box([.82,.1,.72],[0,.62,0],blue,chair,.1);box([.78,.85,.13],[0,1.05,.3],M(0x287d9b,.42,.08),chair,.09);cyl(.05,.4,[0,.34,0],metal,chair);obstacles.push({x,z,w:2.8,d:1.4})};desks.forEach(p=>desk(p[0],p[1],p[1]>0?Math.PI:0));
const sofa=(x:number,z:number)=>{box([1.65,.18,.75],[x,.55,z],M(0x155b74,.43,.08),root,.13);box([1.55,.75,.14],[x,1,z+.34],M(0x1c718b,.42,.08),root,.1)};[-7.8,-5.8,-3.8,3.8,5.8,7.8].forEach(x=>sofa(x,7.25));box([4.4,.18,1.8],[0,.95,-2.2],wood,root,.1);cyl(.45,.08,[0,.55,-2.2],metal);obstacles.push({x:0,z:-2.2,w:4.7,d:2});box([2.2,1.9,.8],[-12,.95,1.8],M(0xd7dde0,.35,.1));box([1.5,.28,.06],[-12,1.5,1.3],screen,root,.02);box([2.1,2.2,.65],[11.8,1.1,-2],M(0x242e34,.55,.4));obstacles.push({x:-12,z:1.8,w:2,d:1.4},{x:11.8,z:-2,w:2.3,d:1.5});cyl(.36,.9,[-11.5,.55,-3],M(0x2d91a9,.25,.18));cyl(.26,.42,[-11.5,1.2,-3],M(0x79d7e5,.15,.05));
for(const [x,z] of[[-13,-7.8],[13,-7.8],[-13,7.8],[13,7.8]]){cyl(.3,.4,[x,.2,z],M(0x5b402c,.8));for(let i=0;i<8;i++){const a=i*Math.PI/4;const leaf=new THREE.Mesh(new THREE.SphereGeometry(.11,10,8),M(i%2?0x287a52:0x3d9866,.7));leaf.position.set(x+Math.cos(a)*.2,.62+(i%3)*.08,z+Math.sin(a)*.2);leaf.scale.set(.6,1.5,.55);root.add(leaf)}}
const blocked=(x:number,z:number,r=.48)=>x<-13.6+r||x>13.6-r||z<-8.3+r||z>8.3-r||obstacles.some(o=>Math.abs(x-o.x)<o.w/2+r&&Math.abs(z-o.z)<o.d/2+r);const moveSafe=(g:THREE.Group,dx:number,dz:number)=>{const nx=g.position.x+dx,nz=g.position.z+dz;if(!blocked(nx,g.position.z))g.position.x=nx;if(!blocked(g.position.x,nz))g.position.z=nz};
const actors:Actor[]=[];let template:THREE.Object3D|null=null;let clips:THREE.AnimationClip[]=[];const loader=new GLTFLoader();const play=(a:Actor,n:'idle'|'walk'|'run')=>{const key=Object.keys(a.actions).find(k=>k.toLowerCase()===n);if(!key)return;const next=a.actions[key];if(next===a.active)return;if(a.active)a.active.fadeOut(.25);next.reset().setEffectiveTimeScale(n==='run'?1.08:1).setEffectiveWeight(1).fadeIn(.25).play();a.active=next};
const dress=(model:THREE.Object3D,index:number)=>{const suit=M([0x17283a,0x24364b,0x3b2930,0x20352c,0x30333b,0x4a392c][index%6],.55,.14);const tie=M([0x1b7187,0x8d2934,0xb47b27,0x2c526e][index%4],.42,.08);model.traverse(o=>{const m=o as THREE.Mesh;if(!m.isMesh)return;m.castShadow=true;m.receiveShadow=true;const n=(m.name+' '+((m.material as any)?.name||'')).toLowerCase();if(n.includes('hair')||n.includes('skin')||n.includes('head')||n.includes('eye'))return;const mm=(m.material as THREE.MeshStandardMaterial).clone?.() as THREE.MeshStandardMaterial|undefined;if(mm){if(n.includes('shoe'))mm.color.set(0x101216);else mm.color.copy(suit.color);mm.roughness=.58;m.material=mm}});const spine=model.getObjectByName('mixamorigSpine2')||model.getObjectByName('Spine2')||model.getObjectByName('Spine');if(spine){box([.58,.72,.26],[0,.04,.01],suit,spine,.1);box([.05,.26,.025],[0,.12,-.17],tie,spine,.01)}const head=model.getObjectByName('mixamorigHead')||model.getObjectByName('Head');if(head){const hair=new THREE.Mesh(new THREE.SphereGeometry(.3,20,12,0,Math.PI*2,0,Math.PI*.56),M([0x171311,0x2b1c16,0x101316,0x3b291f][index%4],.8));hair.position.y=.08;head.add(hair)}};
const addActor=(x:number,z:number,i:number,visitor=false)=>{if(!template)return;const g=new THREE.Group();g.position.set(x,0,z);root.add(g);const model=SkeletonUtils.clone(template);model.scale.setScalar(.92);g.add(model);dress(model,i);const mixer=new THREE.AnimationMixer(model);const actions:Record<string,THREE.AnimationAction>={};clips.forEach(c=>actions[c.name]=mixer.clipAction(c));const a:Actor={g,model,mixer,actions,home:new THREE.Vector3(x,0,z),phase:i*1.31,speed:.72+(i%3)*.12,visitor,state:visitor?'wait':'idle'};actors.push(a);play(a,'idle')};
(async()=>{try{const gltf=await new Promise<any>((resolve,reject)=>loader.load(MODEL,resolve,undefined,reject));if(dead)return;template=gltf.scene;clips=gltf.animations||[];for(let i=0;i<Math.min(agents.length,8);i++){const p=desks[i];addActor(p[0],p[1]+(i<4?.7:-.7),i)}for(let i=0;i<4;i++)addActor(-6+i*2,7.05,20+i,true);setLoading(false)}catch(e){console.warn('Human GLB failed',e);setLoading(false);setFailed(true)}})();
const keys=new Set<string>();const down=(e:KeyboardEvent)=>{const k=e.key.toLowerCase();keys.add(k);if(['w','a','s','d','shift',' '].includes(k))e.preventDefault()};const up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());window.addEventListener('keydown',down);window.addEventListener('keyup',up);const clock=new THREE.Clock();const animate=()=>{if(dead)return;raf=requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;const p=actors[0];if(p){let x=0,z=0;if(keys.has('w'))z-=1;if(keys.has('s'))z+=1;if(keys.has('a'))x-=1;if(keys.has('d'))x+=1;const moving=!!(x||z);if(moving){const l=Math.hypot(x,z)||1;const run=keys.has('shift');const sp=(run?3.1:1.8)*dt;moveSafe(p.g,x/l*sp,z/l*sp);p.g.rotation.y=Math.atan2(x,z);play(p,run?'run':'walk')}else play(p,'idle');p.mixer.update(dt)}actors.slice(1).forEach((a,i)=>{const task=taskRef.current;const working=!!task&&((task.agentId&&agents[i+1]?.id===task.agentId)||(task.agentName&&agents[i+1]?.name===task.agentName));if(a.visitor){const tx=a.home.x+Math.sin(t*.25+a.phase)*.35,tz=a.home.z+Math.cos(t*.2+a.phase)*.18;moveSafe(a.g,(tx-a.g.position.x)*dt*.5,(tz-a.g.position.z)*dt*.5);play(a,'idle')}else if(working){play(a,'idle')}else{const tx=a.home.x+Math.sin(t*.2+a.phase)*.7,tz=a.home.z+Math.cos(t*.17+a.phase)*.45;const dx=tx-a.g.position.x,dz=tz-a.g.position.z,l=Math.hypot(dx,dz);if(l>.15){moveSafe(a.g,dx/l*a.speed*dt,dz/l*a.speed*dt);a.g.rotation.y=Math.atan2(dx,dz);play(a,'walk')}else play(a,'idle')}a.mixer.update(dt)});if(viewRef.current==='top'){camera.position.lerp(new THREE.Vector3(0,29,.01),.06);controls.target.lerp(new THREE.Vector3(0,0,0),.08);controls.maxPolarAngle=Math.PI/2-.01}else{const target=p?new THREE.Vector3(p.g.position.x,1.2,p.g.position.z):new THREE.Vector3(0,1,0);controls.target.lerp(target,.1);if(p)camera.position.lerp(new THREE.Vector3(p.g.position.x+8,p.g.position.y+5.2,p.g.position.z+8),.06);controls.maxPolarAngle=1.43}controls.update();renderer.render(scene,camera)};animate();const resize=()=>{const w=el.clientWidth||900,h=el.clientHeight||600;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};const ro=new ResizeObserver(resize);ro.observe(el);resize();return()=>{dead=true;cancelAnimationFrame(raf);ro.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);controls.dispose();renderer.dispose();actors.forEach(a=>a.mixer.stopAllAction())}},[agents]);
if(failed)return <div className="grid h-full place-items-center bg-[#050a10] text-xs text-red-300">3D character asset could not be loaded.</div>;return <div className="relative h-full w-full"><div ref={host} className="h-full w-full"/>{loading&&<div className="absolute inset-0 grid place-items-center bg-[#050a10]/80 text-[11px] font-bold tracking-[.16em] text-cyan-200 backdrop-blur-sm">LOADING REAL HUMAN CHARACTERS…</div>}<div className="pointer-events-auto absolute right-3 top-3 z-20 flex gap-1"><button onClick={()=>setView('top')} className={`rounded-lg border px-3 py-2 text-[9px] font-black ${view==='top'?'border-cyan-300/40 bg-cyan-300/15 text-cyan-200':'border-white/15 bg-black/50 text-white/70'}`}>TOP VIEW</button><button onClick={()=>setView('3d')} className={`rounded-lg border px-3 py-2 text-[9px] font-black ${view==='3d'?'border-cyan-300/40 bg-cyan-300/15 text-cyan-200':'border-white/15 bg-black/50 text-white/70'}`}>3D VIEW</button></div><div className="pointer-events-none absolute bottom-3 left-3 z-20 rounded-lg border border-white/10 bg-black/55 px-3 py-2 text-[8px] text-slate-300 backdrop-blur">REAL HUMAN MODEL · OFFICE DRESS · HAIR · IDLE/WALK/RUN · COLLISION SAFE · 4 VISITORS</div></div>};
export default OfficeSimulation3DRealistic;
