import React,{useRef,useState}from'react';
import{ArrowUp,FileText,X,RotateCcw,Paperclip,Mic,Download,RefreshCw}from'lucide-react';
import{AgentDefinition,AttachedFile,JarvisSettings,TaskRecord}from'../types';
import{FileDropzone}from'./FileDropzone';
import{VoiceAssistant}from'./VoiceAssistant';
import{TaskPipelineStepper}from'./TaskPipelineStepper';
import{ResultViewer}from'./ResultViewer';
import{OfficeSimulation3DHyperReal as OfficeSimulation3D}from'./OfficeSimulation3DHyperReal';
import{ApiService}from'../services/api';
interface Props{agents:AgentDefinition[];selectedAgentId:string;setSelectedAgentId:(id:string)=>void;settings:JarvisSettings;activeTask:TaskRecord|null;setActiveTask:(t:TaskRecord|null)=>void;onTaskCompleted:(t:TaskRecord)=>void;onAgentHired?:()=>void;recentTasks:TaskRecord[]}
type Msg={id:string;role:'user'|'assistant';content:string;actions?:string[]};
type ChatHistory=Array<{role:'user'|'assistant';content:string}>;
const quick=[['Create NEET Paper','Create a NEET Physics paper with bilingual English-Hindi questions and options.'],['Make DPP','Create a NEET DPP with questions, answer key and detailed solutions.'],['PDF to Word','Read the attached PDF and convert it into a clean bilingual Word document.'],['Academy Notice','Create a professional Shaheen Academy Jaipur notice for an upcoming mock test.']];
const getActions=(text:string)=>{const t=text.toLowerCase();if(/pdf|word|docx|document/.test(t))return['Open result','Download file','Make another'];if(/paper|dpp|question|test|exam/.test(t))return['Make PDF','Make Word','Create another'];if(/notice|poster|social|instagram|facebook|reel/.test(t))return['Make another','Change design'];return['Tell me more','Do this','Create a document']};
export const OfficeAssistant:React.FC<Props>=p=>{const{agents,selectedAgentId,setSelectedAgentId,settings,activeTask,setActiveTask,onTaskCompleted,onAgentHired,recentTasks}=p;const[messages,setMessages]=useState<Msg[]>([{id:'welcome',role:'assistant',content:'Hello Boss 👋 I’m JARVIS. What do you need?',actions:['Create NEET Paper','Make DPP','PDF to Word']}]);const[prompt,setPrompt]=useState('');const[files,setFiles]=useState<AttachedFile[]>([]);const[busy,setBusy]=useState(false);const ref=useRef<HTMLTextAreaElement>(null);const enabled=agents.filter(a=>a.enabled);const completed=recentTasks.filter(t=>t.status==='completed').length;
const reset=()=>{setMessages([{id:Date.now().toString(),role:'assistant',content:'Ready, Boss. What shall I do?',actions:['Create NEET Paper','Make DPP','PDF to Word']}]);setPrompt('');setFiles([]);setActiveTask(null)};
const execute=async(userText:string,history:ChatHistory)=>{setBusy(true);const pending:TaskRecord={id:`p${Date.now()}`,title:userText.slice(0,90),userPrompt:userText,agentId:selectedAgentId==='auto'?'jarvis':selectedAgentId,agentName:selectedAgentId==='auto'?'JARVIS':(enabled.find(a=>a.id===selectedAgentId)?.name||'JARVIS'),status:'understanding',createdAt:new Date().toISOString(),steps:[{status:'understanding',label:'JARVIS is processing the request',timestamp:new Date().toISOString()}],attachedFiles:[...files]};setActiveTask(pending);try{const t=await ApiService.executeTask({userPrompt:userText,selectedAgentId,attachedFiles:files,model:settings.aiModel,settings,history});setActiveTask(t);if(t.agentId==='conversational-core'){setMessages(m=>[...m,{id:`a${Date.now()}`,role:'assistant',content:t.result?.rawText||'Done, Boss.',actions:getActions(t.result?.rawText||'')}]);setActiveTask(null)}else{if(t.steps?.some(s=>s.label.toLowerCase().includes('hr hired')))onAgentHired?.();onTaskCompleted(t);if(t.result?.rawText)setMessages(m=>[...m,{id:`a${Date.now()}`,role:'assistant',content:t.result.rawText,actions:getActions(t.result.rawText)}])}}catch(e:any){setMessages(m=>[...m,{id:`e${Date.now()}`,role:'assistant',content:`Sorry Boss, ${e?.message||'something went wrong'}.`,actions:['Retry']}]);setActiveTask({...pending,status:'failed',error:e?.message||'Something went wrong',completedAt:new Date().toISOString()})}finally{setBusy(false);setFiles([])}};
const send=(custom?:string)=>{const text=(custom??prompt).trim();if(!text&&!files.length)return;const userText=text||'Process the attached file.';const history=messages.slice(-12).map(m=>({role:m.role,content:m.content}));setMessages(m=>[...m,{id:`u${Date.now()}`,role:'user',content:userText}]);setPrompt('');void execute(userText,history)};
const action=(a:string)=>{if(a==='Retry'&&activeTask){void execute(activeTask.userPrompt,messages.slice(-12).map(m=>({role:m.role,content:m.content})));return}if(a==='Open result')return;if(a==='Download file')return;if(a==='Make another'||a==='Create another'){setPrompt('Create another one like the last result.');ref.current?.focus();return}if(a==='Tell me more'){setPrompt('Explain this in more detail.');ref.current?.focus();return}if(a==='Change design'){setPrompt('Make a better professional design.');ref.current?.focus();return}setPrompt(a);ref.current?.focus()};
return <div className="mx-auto w-full max-w-[1500px] text-slate-200"><header className="mb-3 flex items-center justify-between gap-3 rounded-2xl border border-slate-700 bg-[#0c141b] px-4 py-3 shadow-lg"><div><div className="flex items-center gap-2 text-sm font-black text-white">🤖 JARVIS <span className="rounded-full bg-emerald-400/10 px-2 py-0.5 text-[8px] text-emerald-300">ONLINE</span></div><div className="text-[9px] text-slate-500">AI Assistant · {enabled.length} employees · {completed} missions completed</div></div><button onClick={reset} className="rounded-lg border border-slate-700 px-3 py-1.5 text-xs text-slate-400 hover:text-white"><RotateCcw className="mr-1 inline h-3 w-3"/>New chat</button></header>
<div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_minmax(360px,42%)] lg:items-start"><section className="order-2 min-w-0 rounded-2xl border border-slate-700 bg-[#080f15] shadow-xl lg:order-1"><div className="flex h-[min(62vh,620px)] flex-col"><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map(m=><div key={m.id} className={m.role==='user'?'flex justify-end':'flex justify-start'}><div className={m.role==='user'?'max-w-[85%] rounded-2xl rounded-br-md bg-cyan-300 px-4 py-2.5 text-sm text-slate-950':'max-w-[88%] rounded-2xl rounded-bl-md border border-white/10 bg-[#111b24] px-4 py-3 text-sm text-slate-200'}><div className="whitespace-pre-wrap">{m.content}</div>{m.role==='assistant'&&m.actions&&<div className="mt-3 flex flex-wrap gap-1.5">{m.actions.map(a=><button key={a} onClick={()=>action(a)} className="rounded-full border border-cyan-300/20 bg-cyan-300/5 px-3 py-1.5 text-[9px] font-semibold text-cyan-200 hover:bg-cyan-300/10">{a}</button>)}</div>}</div></div>)}{busy&&<div className="flex items-center gap-2 text-[10px] text-slate-500"><span className="h-2 w-2 animate-pulse rounded-full bg-cyan-300"/>JARVIS is working…</div>}</div>{activeTask&&activeTask.status!=='completed'&&<div className="border-t border-white/5 px-4 py-2"><TaskPipelineStepper task={activeTask} onRetry={()=>void execute(activeTask.userPrompt,messages.slice(-12).map(m=>({role:m.role,content:m.content})))}/></div>}
<div className="border-t border-white/10 p-3"><div className="flex items-end gap-2 rounded-2xl border border-slate-700 bg-[#0a1118] p-2 focus-within:border-cyan-300/40">{files.length>0&&<div className="absolute">{files.map(f=><span key={f.id} className="rounded bg-cyan-300/10 px-2 py-1 text-[9px] text-cyan-200">{f.name}<button onClick={()=>setFiles(x=>x.filter(y=>y.id!==f.id))}><X className="ml-1 inline h-3 w-3"/></button></span>)}</div>}<FileDropzone attachedFiles={files} onAddFiles={x=>setFiles(v=>[...v,...x])} onRemoveFile={id=>setFiles(v=>v.filter(x=>x.id!==id))} disabled={busy}/><VoiceAssistant onSpeechResult={t=>setPrompt(x=>x?`${x} ${t}`:t)} onCommandReady={t=>send(t)} isProcessing={busy}/><textarea ref={ref} value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} rows={1} placeholder="Ask JARVIS anything…" className="min-h-[42px] flex-1 resize-none bg-transparent px-2 py-2 text-sm text-white outline-none placeholder:text-slate-600" disabled={busy}/><button onClick={()=>send()} disabled={busy||(!prompt.trim()&&!files.length)} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-cyan-300 text-slate-950 disabled:opacity-30"><ArrowUp className="h-4 w-4"/></button></div><div className="mt-2 flex flex-wrap gap-1.5">{quick.map(([label,text])=><button key={label} onClick={()=>send(text)} className="rounded-full border border-slate-700 bg-white/[.02] px-2.5 py-1.5 text-[9px] text-slate-400 hover:border-cyan-300/25 hover:text-cyan-200">{label}</button>)}</div></div></div></section>
<aside className="order-1 min-w-0 lg:order-2"><OfficeSimulation3D agents={enabled} activeTask={activeTask}/>{activeTask?.status==='completed'&&activeTask.result&&<div className="mt-3 rounded-2xl border border-slate-700 bg-[#0c141b] p-3"><ResultViewer task={activeTask} onRepeat={()=>setPrompt(activeTask.userPrompt)}/></div>}</aside></div></div>};