import React, { useEffect, useRef } from 'react';
import { AgentDefinition, TaskRecord } from '../types';

declare global { interface Window { THREE?: any; } }
interface Props { agents: AgentDefinition[]; activeTask: TaskRecord | null; }

const CDN='https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.min.js';
const SUITS=[0x20c7ca,0x5b8def,0xe5a83b,0xe66bb5,0x9b7bea,0x35c99b,0xf06d6d,0x3bb6df];
const SKIN=[0xf1c39f,0xd9a27c,0x8f6046,0xf0c6a4,0xc98563,0xf1b98e];

function loadThree(){return new Promise<any>((resolve,reject)=>{if(window.THREE)return resolve(window.THREE);const old=document.querySelector(`script[src="${CDN}"]`);if(old){old.addEventListener('load',()=>resolve(window.THREE));old.addEventListener('error',reject);return;}const s=document.createElement('script');s.src=CDN;s.async=true;s.onload=()=>resolve(window.THREE);s.onerror=reject;document.head.appendChild(s);});}

export const OfficeSimulation3D:React.FC<Props>=({agents,activeTask})=>{
 const host=useRef<HTMLDivElement>(null); const taskRef=useRef< TaskRecord|null >(activeTask); taskRef.current=activeTask;
 useEffect(()=>{let disposed=false;let renderer:any,camera:any,scene:any,raf=0;const workers:any[]=[];let jarvis:any,boss:any;let ray:any;let dragging=false,lastX=0,lastY=0,theta=.72,phi=.96,radius=29;
 const init=async()=>{const T=await loadThree();if(disposed||!host.current)return;
  scene=new T.Scene();scene.background=new T.Color(0x071018);scene.fog=new T.Fog(0x071018,24,55);
  camera=new T.PerspectiveCamera(48,1,.1,100);renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;host.current.innerHTML='';host.current.appendChild(renderer.domElement);
  const hemi=new T.HemisphereLight(0xbfefff,0x101820,2.1);scene.add(hemi);const key=new T.DirectionalLight(0xffffff,3.2);key.position.set(10,22,10);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-24;key.shadow.camera.right=24;key.shadow.camera.top=22;key.shadow.camera.bottom=-22;scene.add(key);const cyan=new T.PointLight(0x22d3ee,55,18);cyan.position.set(0,7,0);scene.add(cyan);
  const mat=(c:number,rough=.55,metal=.05)=>new T.MeshStandardMaterial({color:c,roughness:rough,metalness:metal});
  const floor=new T.Mesh(new T.BoxGeometry(28,.35,20),mat(0x17232b,.72));floor.position.y=-.2;floor.receiveShadow=true;scene.add(floor);
  const grid=new T.GridHelper(28,28,0x36515c,0x243740);grid.position.y=-.01;grid.material.opacity=.34;grid.material.transparent=true;scene.add(grid);
  const wallMat=mat(0x263640,.8); const glass=new T.MeshPhysicalMaterial({color:0x7dd3fc,transparent:true,opacity:.09,roughness:.2,metalness:.15});
  const wall=(x:number,y:number,z:number,w:number,d:number,transparent=false)=>{const m=new T.Mesh(new T.BoxGeometry(w,2.4,d),transparent?glass:wallMat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;};
  wall(0,1.2,-9.7,28,.35);wall(-13.8,1.2,0,.35,19.4);wall(13.8,1.2,0,.35,19.4);wall(-6.8,1.2,-4.6,.18,9.2,true);wall(0,1.2,-4.6,.18,9.2,true);wall(6.8,1.2,-4.6,.18,9.2,true);wall(-6.8,1.2,4.7,.18,9,true);wall(0,1.2,4.7,.18,9,true);wall(6.8,1.2,4.7,.18,9,true);
  const roomNames=[['PAPER LAB',-10,-6.9],['DOCUMENTS',-3.4,-6.9],['DPP ROOM',3.4,-6.9],['DESIGN STUDIO',10,-6.9],['RESEARCH',-10,6.8],['QA ROOM',-3.4,6.8],['MEDIA LAB',3.4,6.8],['DATA / FILES',10,6.8]];
  const label=(text:string,x:number,y:number,z:number=0)=>{const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,512,96);ctx.fillStyle='rgba(4,12,18,.82)';ctx.roundRect(8,8,496,80,18);ctx.fill();ctx.font='700 30px Arial';ctx.fillStyle='#bceff5';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,48);const tx=new T.CanvasTexture(c);const sp=new T.Sprite(new T.SpriteMaterial({map:tx,transparent:true}));sp.scale.set(4.3,.8,1);sp.position.set(x,y,z);scene.add(sp);return sp;};
  roomNames.forEach(r=>label(r[0] as string,r[1] as number,2.7,r[2] as number));label('SHAHEEN AI OFFICE',0,8.4,-9.45);
  const box=(x:number,z:number,sx:number,sy:number,sz:number,c:number)=>{const m=new T.Mesh(new T.BoxGeometry(sx,sy,sz),mat(c));m.position.set(x,sy/2-.02,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;};
  const desk=(x:number,z:number,rot=0)=>{const g=new T.Group();g.position.set(x,0,z);g.rotation.y=rot;const top=box(0,0,2.7,.18,1.35,0x5b4030);top.position.y=1.35;g.add(top);[-1.05,1.05].forEach(px=>{const leg=box(0,0,.13,1.3,.13,0x2a2020);leg.position.set(px,0,0);g.add(leg);});const mon=new T.Mesh(new T.BoxGeometry(1.25,.82,.08),mat(0x202b33,.35,.3));mon.position.set(0,1.85,-.2);g.add(mon);const glow=new T.Mesh(new T.PlaneGeometry(1.08,.62),new T.MeshBasicMaterial({color:0x08202a}));glow.position.set(0,1.85,-.25);g.add(glow);const kb=box(0,.35,.9,.035,.35,0x89949b);kb.position.set(0,1.47,.22);g.add(kb);scene.add(g);return g;};
  const homes=[[-10,-5.3],[-3.4,-5.3],[3.4,-5.3],[10,-5.3],[-10,5.3],[-3.4,5.3],[3.4,5.3],[10,5.3]];
  const person=(name:string,i:number,x:number,z:number)=>{const g=new T.Group();g.position.set(x,0,z);const suit=mat(SUITS[i%SUITS.length],.52);const skin=mat(SKIN[i%SKIN.length],.7);const body=new T.Mesh(new T.CapsuleGeometry(.38,1.0,6,12),suit);body.position.y=1.15;body.castShadow=true;g.add(body);const head=new T.Mesh(new T.SphereGeometry(.34,18,14),skin);head.position.y=2.15;head.castShadow=true;g.add(head);const hair=new T.Mesh(new T.SphereGeometry(.36,16,10,0,Math.PI*2,0,Math.PI*.38),mat(0x22252a,.9));hair.position.y=2.28;g.add(hair);for(const sx of [-.22,.22]){const arm=new T.Mesh(new T.CapsuleGeometry(.09,.7,5,8),suit);arm.position.set(sx,1.15,0);arm.rotation.z=sx<0?-0.22:0.22;arm.castShadow=true;g.add(arm);}for(const sx of [-.14,.14]){const leg=new T.Mesh(new T.CapsuleGeometry(.1,.75,5,8),mat(0x202833));leg.position.set(sx,.38,0);leg.castShadow=true;g.add(leg);}const ring=new T.Mesh(new T.TorusGeometry(.52,.025,8,32),new T.MeshBasicMaterial({color:SUITS[i%SUITS.length],transparent:true,opacity:.65}));ring.rotation.x=Math.PI/2;ring.position.y=.04;g.add(ring);const plate=label(name.length>17?name.slice(0,16)+'…':name,x,3.05,z);plate.scale.set(2.4,.45,1);g.userData={home:new T.Vector3(x,0,z),body,arms:g.children.filter((o:any)=>o.geometry?.type==='CapsuleGeometry'),plate,busy:false,index:i,phase:i*.8};scene.add(g);return g;};
  homes.forEach((p,i)=>{desk(p[0] as number,p[1] as number,i<4?0:Math.PI);if(agents[i])workers.push(person(agents[i].name,i,p[0] as number,p[1] as number));});
  const managerDesk=box(0,-1.9,3.8,.22,1.5,0x2d4851);managerDesk.position.y=1.2;const mgr=new T.Group();mgr.position.set(0,0,-1.8);jarvis=person('JARVIS',7,0,-1.8);jarvis.scale.setScalar(1.08);label('JARVIS • MANAGER',0,3.25,-1.8).scale.set(3.2,.52,1);scene.add(mgr);
  boss=person('BOSS / CEO',6,10,5.8);boss.scale.setScalar(1.08);desk(10,7.1,Math.PI);label('YOUR COMMAND DESK',10,2.55,7.1).scale.set(3,.5,1);
  const coffee=box(0,0,2.2,.65,1.1,0x3c2b22);coffee.position.set(0,.33,1.3);const mug=new T.Mesh(new T.CylinderGeometry(.18,.22,.3,16),mat(0xc79a63));mug.position.set(.55,.9,1.3);scene.add(coffee,mug);label('☕ BREAK AREA',0,1.55,1.3).scale.set(2.5,.45,1);
  const neon=new T.Mesh(new T.BoxGeometry(7,.05,.05),new T.MeshBasicMaterial({color:0x22d3ee}));neon.position.set(0,3.1,-9.45);scene.add(neon);
  const resize=()=>{if(!host.current||!renderer)return;const w=host.current.clientWidth,h=host.current.clientHeight||650;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();};resize();window.addEventListener('resize',resize);
  const onDown=(e:PointerEvent)=>{dragging=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId);};const onUp=()=>{dragging=false;};const onMove=(e:PointerEvent)=>{if(!dragging)return;theta-=(e.clientX-lastX)*.008;phi=Math.max(.45,Math.min(1.38,phi+(e.clientY-lastY)*.006));lastX=e.clientX;lastY=e.clientY;};const onWheel=(e:WheelEvent)=>{radius=Math.max(18,Math.min(40,radius+e.deltaY*.018));};renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',onUp);renderer.domElement.addEventListener('pointermove',onMove);renderer.domElement.addEventListener('wheel',onWheel,{passive:true});
  const route=(g:any,target:any)=>{g.userData.target=target.clone();g.userData.busy=true;};let lastTask='';
  const tick=(time:number)=>{if(disposed)return;raf=requestAnimationFrame(tick);const task=taskRef.current;if(task?.id&&task.id!==lastTask){lastTask=task.id;const idx=Math.max(0,workers.findIndex(w=>w.userData.name===task.agentName||w.userData.agent?.name===task.agentName));const w=workers[idx];if(w){w.userData.busy=true;route(w,new T.Vector3(0,0,-1.8));}}
    workers.forEach((g:any,i:number)=>{const u=g.userData;const target=u.target;if(target){const dx=target.x-g.position.x,dz=target.z-g.position.z;const dist=Math.hypot(dx,dz);if(dist>.12){g.position.x+=dx*.045;g.position.z+=dz*.045;g.rotation.y=Math.atan2(dx,dz);u.body.position.y=1.15+Math.sin(time*.012+i)*.025;}else{if(u.busy&&taskRef.current){u.target=u.home.clone();u.busy=false;}else if(Math.sin(time*.00035+i)>0.97&&!u.busy){u.target=new T.Vector3(u.home.x+(Math.random()-.5)*1.4,0,u.home.z+(Math.random()-.5)*.8);}}}u.plate.position.set(g.position.x,3.05,g.position.z);});
    if(jarvis){jarvis.position.y=.06+Math.sin(time*.0015)*.035;}if(boss)boss.position.y=.02+Math.sin(time*.0012)*.02;
    camera.position.set(Math.sin(theta)*radius*Math.sin(phi),radius*Math.cos(phi),Math.cos(theta)*radius*Math.sin(phi));camera.lookAt(0,0,0);renderer.render(scene,camera);};tick(performance.now());
 };
 init().catch(console.error);return()=>{disposed=true;cancelAnimationFrame(raf);window.removeEventListener('resize',()=>{});renderer?.dispose();if(host.current)host.current.innerHTML='';};
 },[agents]);
 return <div className="relative w-full overflow-hidden rounded-[26px] border border-cyan-300/15 bg-[#071018] shadow-[0_30px_100px_rgba(0,0,0,.55)]"><div className="pointer-events-none absolute left-4 top-4 z-10 rounded-xl border border-cyan-300/20 bg-[#071017]/90 px-3 py-2 text-[10px] font-bold tracking-[.12em] text-cyan-100 backdrop-blur">3D AI OFFICE · LIVE</div><div className="pointer-events-none absolute bottom-4 left-4 z-10 rounded-lg bg-black/40 px-2 py-1 text-[9px] text-slate-300">Drag = rotate · Wheel = zoom · Missions move employees</div><div ref={host} className="h-[620px] w-full"/></div>;
};
export default OfficeSimulation3D;
