import React, { useState } from 'react';
import {
  Download,
  FileText,
  Copy,
  Check,
  Languages,
  Eye,
  EyeOff,
  Sparkles,
  Share2,
  Printer,
  ChevronDown,
  ChevronUp,
  CheckCircle2,
  GraduationCap,
  Megaphone,
  Clapperboard,
} from 'lucide-react';
import { ExecutionResult, GeneratedArtifact, TaskRecord } from '../types';

interface ResultViewerProps {
  task: TaskRecord;
  onRepeat?: () => void;
}

export const ResultViewer: React.FC<ResultViewerProps> = ({ task, onRepeat }) => {
  const [copied, setCopied] = useState(false);
  const [bilingualMode, setBilingualMode] = useState<'both' | 'en' | 'hi'>('both');
  const [showAnswers, setShowAnswers] = useState(true);
  const [showSolutions, setShowSolutions] = useState(false);
  const [activeTab, setActiveTab] = useState<'preview' | 'raw' | 'artifacts'>('preview');

  const result = task.result;
  if (!result) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(result.rawText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadDocx = (artifact: GeneratedArtifact) => {
    if (!artifact.docxBase64) {
      // Fallback text download
      const blob = new Blob([artifact.content || result.rawText], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = artifact.name;
      a.click();
      URL.revokeObjectURL(url);
      return;
    }

    // Convert base64 to binary blob
    const byteCharacters = atob(artifact.docxBase64);
    const byteNumbers = new Array(byteCharacters.length);
    for (let i = 0; i < byteCharacters.length; i++) {
      byteNumbers[i] = byteCharacters.charCodeAt(i);
    }
    const byteArray = new Uint8Array(byteNumbers);
    const blob = new Blob([byteArray], {
      type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    });

    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = artifact.name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrintPdf = () => {
    window.print();
  };

  const structured = result.structuredData;
  const questions = structured?.questions || [];
  const isPaperOrDpp = questions.length > 0;
  const docxArtifact = result.artifacts?.find((a) => a.fileType === 'docx');

  return (
    <div className="w-full rounded-3xl border border-white/10 bg-white/5 shadow-2xl backdrop-blur-xl overflow-hidden" id="task-result-viewer">
      {/* Top Action Bar */}
      <div className="flex flex-wrap items-center justify-between border-b border-white/10 bg-white/5 px-4 py-3.5 sm:px-6 backdrop-blur-md">
        <div className="flex items-center space-x-2.5">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 shadow-[0_0_15px_rgba(6,182,212,0.25)]">
            {task.agentId.includes('paper') || task.agentId.includes('dpp') ? (
              <GraduationCap className="h-5 w-5" />
            ) : task.agentId.includes('poster') || task.agentId.includes('notice') ? (
              <Megaphone className="h-5 w-5" />
            ) : task.agentId.includes('reel') ? (
              <Clapperboard className="h-5 w-5" />
            ) : (
              <Sparkles className="h-5 w-5" />
            )}
          </div>
          <div>
            <h3 className="text-sm font-bold text-white tracking-tight">
              {structured?.title || task.title}
            </h3>
            <p className="text-[11px] text-cyan-300 font-medium">
              Generated by {task.agentName} • {new Date(task.completedAt || task.createdAt).toLocaleTimeString()}
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="mt-2 flex flex-wrap items-center gap-2 sm:mt-0">
          {docxArtifact && (
            <button
              onClick={() => handleDownloadDocx(docxArtifact)}
              id="btn-download-docx-result"
              className="flex items-center space-x-1.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 px-4 py-2 text-xs font-bold text-white shadow-[0_0_15px_rgba(6,182,212,0.4)] transition-all"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download .DOCX (Word)</span>
            </button>
          )}

          <button
            onClick={handlePrintPdf}
            className="flex items-center space-x-1.5 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-medium text-slate-300 hover:border-white/20 hover:bg-white/10 hover:text-white transition-all backdrop-blur-md"
            title="Print or Save as PDF"
          >
            <Printer className="h-3.5 w-3.5 text-slate-400" />
            <span className="hidden sm:inline">Print / PDF</span>
          </button>

          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-medium text-slate-300 hover:border-white/20 hover:bg-white/10 hover:text-white transition-all backdrop-blur-md"
            title="Copy formatted content"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5 text-slate-400" />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>
        </div>
      </div>

      {/* Mode / View Selector (For Question Papers / DPPs) */}
      {isPaperOrDpp && (
        <div className="flex flex-wrap items-center justify-between border-b border-white/10 bg-white/5 px-4 py-2.5 sm:px-6 backdrop-blur-md">
          {/* Bilingual Language View Toggle */}
          <div className="flex items-center space-x-1 rounded-xl border border-white/10 bg-white/5 p-1 backdrop-blur-md">
            <span className="px-2 text-[10px] font-semibold text-slate-400 uppercase tracking-wider">
              Language:
            </span>
            <button
              onClick={() => setBilingualMode('both')}
              className={`rounded-lg px-2.5 py-1 text-xs font-medium transition-all ${
                bilingualMode === 'both'
                  ? 'bg-cyan-500/20 border border-cyan-500/40 text-cyan-300 shadow-[0_0_10px_rgba(6,182,212,0.25)]'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              Bilingual (Eng + हिंदी)
            </button>
            <button
              onClick={() => setBilingualMode('en')}
              className={`rounded-lg px-2.5 py-1 text-xs font-medium transition-all ${
                bilingualMode === 'en'
                  ? 'bg-cyan-500/20 border border-cyan-500/40 text-cyan-300 shadow-[0_0_10px_rgba(6,182,212,0.25)]'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              English Only
            </button>
            <button
              onClick={() => setBilingualMode('hi')}
              className={`rounded-lg px-2.5 py-1 text-xs font-medium transition-all ${
                bilingualMode === 'hi'
                  ? 'bg-cyan-500/20 border border-cyan-500/40 text-cyan-300 shadow-[0_0_10px_rgba(6,182,212,0.25)]'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              हिंदी Only
            </button>
          </div>

          {/* Quick Toggles */}
          <div className="mt-2 flex items-center space-x-3 sm:mt-0">
            <label className="flex cursor-pointer items-center space-x-1.5 text-xs text-slate-300">
              <input
                type="checkbox"
                checked={showAnswers}
                onChange={(e) => setShowAnswers(e.target.checked)}
                className="rounded border-white/20 bg-white/10 text-cyan-500 focus:ring-cyan-500"
              />
              <span>Answer Key</span>
            </label>

            <label className="flex cursor-pointer items-center space-x-1.5 text-xs text-slate-300">
              <input
                type="checkbox"
                checked={showSolutions}
                onChange={(e) => setShowSolutions(e.target.checked)}
                className="rounded border-white/20 bg-white/10 text-cyan-500 focus:ring-cyan-500"
              />
              <span>Hints & Solutions</span>
            </label>
          </div>
        </div>
      )}

      {/* Main Content Body */}
      <div className="p-4 sm:p-6 max-h-[70vh] overflow-y-auto" id="printable-content">
        {isPaperOrDpp ? (
          <div className="space-y-6">
            {/* Institute & Assessment Banner */}
            <div className="rounded-2xl border border-white/10 bg-white/5 p-5 text-center backdrop-blur-md shadow-lg">
              <h2 className="font-['Space_Grotesk'] text-xl font-bold tracking-tight text-cyan-400 sm:text-2xl uppercase">
                {structured?.instituteName || 'Apex Academy'}
              </h2>
              <h3 className="text-base font-semibold text-white mt-1">
                {structured?.title || 'Academic Question Assessment'}
              </h3>
              <div className="mt-3.5 flex flex-wrap items-center justify-center gap-4 text-xs text-slate-400 border-t border-white/10 pt-2.5">
                <span>Target: <strong className="text-slate-200">{structured?.examType || 'NEET / JEE'}</strong></span>
                <span>•</span>
                <span>Subject: <strong className="text-slate-200">{structured?.subject || 'All Sections'}</strong></span>
                <span>•</span>
                <span>Total Questions: <strong className="text-cyan-400">{questions.length}</strong></span>
                <span>•</span>
                <span>Marking: <strong className="text-slate-200">+4 / -1 Scheme</strong></span>
              </div>
            </div>

            {/* Questions List */}
            <div className="space-y-4">
              {questions.map((q: any, idx: number) => (
                <div
                  key={idx}
                  className="rounded-2xl border border-white/10 bg-white/5 p-4 sm:p-5 transition-all hover:border-cyan-500/30 backdrop-blur-md"
                >
                  {/* Question Stem */}
                  <div className="flex items-start space-x-3">
                    <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-cyan-500/20 text-xs font-bold text-cyan-300 border border-cyan-500/30 shadow-[0_0_10px_rgba(6,182,212,0.2)]">
                      {q.number || idx + 1}
                    </span>
                    <div className="flex-1 space-y-1.5">
                      {(bilingualMode === 'both' || bilingualMode === 'en') && (
                        <p className="text-sm font-semibold text-slate-100 leading-relaxed font-sans">
                          {q.textEn}
                        </p>
                      )}
                      {(bilingualMode === 'both' || bilingualMode === 'hi') && q.textHi && (
                        <p className="text-sm font-medium text-slate-300 leading-relaxed font-['Noto_Sans_Devanagari'] text-cyan-100/90">
                          {q.textHi}
                        </p>
                      )}
                    </div>
                  </div>

                  {/* Options (A, B, C, D) */}
                  {q.optionsEn && q.optionsEn.length > 0 && (
                    <div className="mt-3.5 grid grid-cols-1 gap-2.5 pl-9 sm:grid-cols-2">
                      {q.optionsEn.map((opt: string, optIdx: number) => {
                        const optLetter = String.fromCharCode(65 + optIdx);
                        const isCorrect = showAnswers && q.correctOption && q.correctOption.includes(optLetter);

                        return (
                          <div
                            key={optIdx}
                            className={`flex items-start space-x-2.5 rounded-xl border p-2.5 text-xs transition-all ${
                              isCorrect
                                ? 'border-emerald-500/60 bg-emerald-500/10 text-emerald-200 ring-1 ring-emerald-500/30 shadow-[0_0_12px_rgba(16,185,129,0.15)]'
                                : 'border-white/10 bg-white/5 text-slate-300'
                            }`}
                          >
                            <span
                              className={`flex h-5 w-5 shrink-0 items-center justify-center rounded-lg text-[11px] font-bold ${
                                isCorrect
                                  ? 'bg-emerald-500 text-slate-950'
                                  : 'bg-white/10 text-cyan-400'
                              }`}
                            >
                              {optLetter}
                            </span>
                            <div className="flex-1 leading-snug">
                              <span>{opt}</span>
                              {q.optionsHi && q.optionsHi[optIdx] && bilingualMode === 'both' && (
                                <span className="block text-slate-400 font-['Noto_Sans_Devanagari'] mt-0.5">
                                  {q.optionsHi[optIdx]}
                                </span>
                              )}
                            </div>
                            {isCorrect && (
                              <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-400" />
                            )}
                          </div>
                        );
                      })}
                    </div>
                  )}

                  {/* Hints / Solutions section */}
                  {showSolutions && q.solution && (
                    <div className="mt-3 pl-9">
                      <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/10 p-3 text-xs text-cyan-200 backdrop-blur-md">
                        <strong className="text-cyan-300">Solution / हल: </strong>
                        <span>{q.solution}</span>
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>

            {/* Answer Key Grid */}
            {showAnswers && (
              <div className="rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-5 backdrop-blur-md shadow-lg">
                <h4 className="text-xs font-bold uppercase tracking-wider text-emerald-400 mb-3 flex items-center space-x-2">
                  <CheckCircle2 className="h-4 w-4" />
                  <span>Answer Key / उत्तर कुंजी</span>
                </h4>
                <div className="grid grid-cols-5 gap-2 sm:grid-cols-10">
                  {questions.map((q: any, i: number) => (
                    <div
                      key={i}
                      className="flex flex-col items-center justify-center rounded-xl border border-emerald-500/30 bg-slate-900/80 p-2 text-center shadow-sm"
                    >
                      <span className="text-[10px] text-slate-400">Q.{q.number || i + 1}</span>
                      <span className="text-sm font-bold text-emerald-300">
                        {q.correctOption || '-'}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : (
          /* Notice / Script / Social Media / General Output Render */
          <div className="prose prose-invert max-w-none">
            <div className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-slate-200">
              {result.rawText}
            </div>
          </div>
        )}
      </div>

      {/* Bottom Footer with Artifacts summary */}
      <div className="flex flex-wrap items-center justify-between border-t border-white/10 bg-white/5 px-4 py-3 sm:px-6 text-xs text-slate-400 backdrop-blur-md">
        <div className="flex items-center space-x-2">
          <FileText className="h-4 w-4 text-cyan-400" />
          <span>
            {result.artifacts?.length || 0} artifact(s) generated ready for export
          </span>
        </div>

        {onRepeat && (
          <button
            onClick={onRepeat}
            className="text-cyan-400 hover:text-cyan-300 font-medium transition-colors"
          >
            Refine or Repeat with modifications →
          </button>
        )}
      </div>
    </div>
  );
};
