import React, { useMemo } from 'react';
import { AlertTriangle, CheckCircle2, ShieldCheck, RotateCcw } from 'lucide-react';
import { ResultViewerFixed } from './ResultViewerFixed';
import { InputFileDownloads } from './InputFileDownloads';
import { TaskRecord } from '../types';

function requestedCount(prompt:string):number|null{const m=prompt.match(/\b(\d{1,3})\s*(?:questions?|qs?|प्रश्न)\b/i);return m?Number(m[1]):null;}
function reviewTask(task:TaskRecord){
 const checks:{label:string;ok:boolean;detail:string}[]=[]; const result=task.result; const artifacts=result?.artifacts||[];
 checks.push({label:'Execution completed',ok:task.status==='completed',detail:task.status==='completed'?'Task reached completed state.':'Task did not complete successfully.'});
 checks.push({label:'Result payload present',ok:!!result,detail:result?'Execution result received.':'No execution result was returned.'});
 checks.push({label:'Primary output present',ok:!!result?.rawText?.trim()||artifacts.length>0,detail:result?.rawText?.trim()||artifacts.length>0?'Output content/artifact is present.':'No usable output was produced.'});
 checks.push({label:'Artifacts valid',ok:artifacts.every(a=>(a.size||0)>0||!!a.content||!!a.docxBase64||!!a.downloadUrl),detail:artifacts.length?`${artifacts.length} artifact(s) checked.`:'No downloadable artifact was required.'});
 const data:any=result?.structuredData;
 if(Array.isArray(data?.questions)){const qs=data.questions;const expected=requestedCount(task.userPrompt);checks.push({label:'Question count',ok:expected===null||qs.length===expected,detail:expected===null?`${qs.length} question(s) returned.`:`Requested ${expected}, received ${qs.length}.`});const numbering=qs.every((q:any,i:number)=>String(q.number||'').replace(/^Q\.?/i,'')===String(i+1));checks.push({label:'Sequential numbering',ok:numbering,detail:numbering?'Questions are numbered sequentially.':'Question numbering is inconsistent.'});const bilingual=qs.every((q:any)=>String(q.textEn||'').trim()&&String(q.textHi||'').trim());checks.push({label:'English + Hindi questions',ok:bilingual,detail:bilingual?'Every question has both languages.':'One or more questions are missing English or Hindi.'});const options=qs.every((q:any)=>Array.isArray(q.optionsEn)&&q.optionsEn.length===4&&Array.isArray(q.optionsHi)&&q.optionsHi.length===4&&q.optionsEn.every((x:any)=>String(x).trim())&&q.optionsHi.every((x:any)=>String(x).trim()));checks.push({label:'Four bilingual options',ok:options,detail:options?'Every MCQ has four English and four Hindi options.':'One or more MCQs have incomplete options.'});const answers=qs.every((q:any)=>/^[A-D]$/i.test(String(q.correctOption||'')));checks.push({label:'Answer key',ok:answers,detail:answers?'Every question has a valid A–D answer.':'One or more questions have an invalid/missing answer.'});}
 return checks;
}
export const ResultViewer: React.FC<{task: TaskRecord; onRepeat?: () => void}> = ({task,onRepeat}) => {const checks=useMemo(()=>reviewTask(task),[task]);const passed=checks.every(c=>c.ok);return <div className="space-y-3"><section className={`overflow-hidden rounded-2xl border ${passed?'border-emerald-400/20':'border-amber-400/25'} bg-[#08121a] shadow-xl`}><div className="flex items-center justify-between border-b border-white/5 px-4 py-3"><div className="flex items-center gap-3"><div className={`flex h-9 w-9 items-center justify-center rounded-xl ${passed?'bg-emerald-400/10 text-emerald-300':'bg-amber-400/10 text-amber-300'}`}>{passed?<ShieldCheck className="h-4 w-4"/>:<AlertTriangle className="h-4 w-4"/>}</div><div><div className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-200">STEP 4 · QUALITY CONTROL</div><div className="text-[9px] text-slate-500">Deterministic delivery gate</div></div></div><span className={`rounded-full px-2 py-1 text-[8px] font-black ${passed?'bg-emerald-400/10 text-emerald-300':'bg-amber-400/10 text-amber-300'}`}>{passed?'QC PASSED':'QC HOLD'}</span></div><div className="grid gap-2 p-4 md:grid-cols-2">{checks.map(c=><div key={c.label} className="flex gap-2 rounded-xl border border-white/5 bg-black/20 p-3"><div className="mt-0.5">{c.ok?<CheckCircle2 className="h-3.5 w-3.5 text-emerald-300"/>:<AlertTriangle className="h-3.5 w-3.5 text-amber-300"/>}</div><div><div className="text-[10px] font-bold text-slate-200">{c.label}</div><div className="mt-0.5 text-[9px] text-slate-500">{c.detail}</div></div></div>)}</div>{!passed&&<div className="flex items-center justify-between border-t border-white/5 px-4 py-3"><div className="text-[9px] text-amber-200">Delivery is blocked until the output passes QC.</div>{onRepeat&&<button onClick={onRepeat} className="rounded-xl bg-amber-300 px-3 py-2 text-[9px] font-black text-slate-950"><RotateCcw className="mr-1 inline h-3.5 w-3.5"/>RETRY MISSION</button>}</div>}</section>{passed&&<><InputFileDownloads files={task.attachedFiles || []}/><ResultViewerFixed task={task} onRepeat={onRepeat}/></>}</div>;};
