import React, { useState, useEffect } from 'react';
import { AgentDefinition, AttachedFile, JarvisMemoryItem, JarvisSettings, TaskRecord } from './types';
import { ApiService, DEFAULT_SETTINGS } from './services/api';
import { Header } from './components/Header';
import { MainAssistant } from './components/MainAssistant';
import { AgentManager } from './components/AgentManager';
import { FileManager } from './components/FileManager';
import { MemoryManager } from './components/MemoryManager';
import { TaskHistory } from './components/TaskHistory';
import { SettingsModal } from './components/SettingsModal';
import { QuickExamBuilder } from './components/QuickExamBuilder';
import { ResultViewerFixed } from './components/ResultViewerFixed';

export default function App() {
  const [activeTab,setActiveTab]=useState<'assistant'|'agents'|'files'|'memory'|'history'>('assistant');
  const [agents,setAgents]=useState<AgentDefinition[]>([]);const [selectedAgentId,setSelectedAgentId]=useState('auto');const [memories,setMemories]=useState<JarvisMemoryItem[]>([]);const [settings,setSettings]=useState<JarvisSettings>(DEFAULT_SETTINGS);const [tasks,setTasks]=useState<TaskRecord[]>([]);const [activeTask,setActiveTask]=useState<TaskRecord|null>(null);const [uploadedFiles,setUploadedFiles]=useState<AttachedFile[]>([]);const [isSettingsOpen,setIsSettingsOpen]=useState(false);const [isQuickBuilderOpen,setIsQuickBuilderOpen]=useState(false);const [isLoading,setIsLoading]=useState(true);const [isAiConfigured,setIsAiConfigured]=useState(false);
  useEffect(()=>{const init=async()=>{try{const ss=localStorage.getItem('jarvis_settings');if(ss)try{setSettings(JSON.parse(ss));}catch{}const st=localStorage.getItem('jarvis_task_history');if(st)try{const p:TaskRecord[]=JSON.parse(st);setTasks(p);if(p.length)setActiveTask(p[0]);}catch{}const sf=localStorage.getItem('jarvis_uploaded_files');if(sf)try{setUploadedFiles(JSON.parse(sf));}catch{}const [a,m,h]=await Promise.all([ApiService.getAgents(),ApiService.getMemories(),ApiService.checkHealth()]);setAgents(a);setMemories(m);setIsAiConfigured(Boolean(h?.aiConfigured));}catch(e){console.error(e);setIsAiConfigured(false);}finally{setIsLoading(false);}};init();},[]);
  const refreshAgents=async()=>{try{setAgents(await ApiService.getAgents());}catch(e){console.error(e);}};const refreshMemories=async()=>{try{setMemories(await ApiService.getMemories());}catch(e){console.error(e);}};
  const handleSaveSettings=(s:JarvisSettings)=>{setSettings(s);localStorage.setItem('jarvis_settings',JSON.stringify(s));};
  const handleTaskCompleted=(t:TaskRecord)=>{setTasks(p=>{const u=[t,...p.filter(x=>x.id!==t.id)].slice(0,50);localStorage.setItem('jarvis_task_history',JSON.stringify(u));return u;});if(t.attachedFiles?.length)setUploadedFiles(p=>{const map=new Map(p.map(f=>[f.id,f]));t.attachedFiles!.forEach(f=>map.set(f.id,f));const u=Array.from(map.values());localStorage.setItem('jarvis_uploaded_files',JSON.stringify(u));return u;});};
  const handleDeleteTask=(id:string)=>{setTasks(p=>{const u=p.filter(t=>t.id!==id);localStorage.setItem('jarvis_task_history',JSON.stringify(u));return u;});if(activeTask?.id===id)setActiveTask(null);};const handleClearAllHistory=()=>{setTasks([]);setActiveTask(null);localStorage.removeItem('jarvis_task_history');};const handleDeleteUploadedFile=(id:string)=>setUploadedFiles(p=>{const u=p.filter(f=>f.id!==id);localStorage.setItem('jarvis_uploaded_files',JSON.stringify(u));return u;});
  const allGeneratedArtifacts=tasks.flatMap(t=>(t.result?.artifacts||[]).map(artifact=>({artifact,taskTitle:t.title,date:t.completedAt||t.createdAt})));
  return <div className="min-h-screen text-slate-200 font-sans flex flex-col relative overflow-x-hidden"><div className="fixed top-0 left-1/4 -z-10 h-96 w-96 rounded-full bg-cyan-500/10 blur-[120px] pointer-events-none"/><div className="fixed bottom-10 right-1/4 -z-10 h-96 w-96 rounded-full bg-purple-600/10 blur-[140px] pointer-events-none"/><Header activeTab={activeTab} setActiveTab={setActiveTab} onOpenSettings={()=>setIsSettingsOpen(true)} onOpenQuickBuilder={()=>setIsQuickBuilderOpen(true)} isAiConfigured={isAiConfigured} settings={settings} taskCount={tasks.length}/><main className="flex-1 p-3 sm:p-6 md:p-8">
    {activeTab==='assistant'&&<MainAssistant agents={agents} selectedAgentId={selectedAgentId} setSelectedAgentId={setSelectedAgentId} settings={settings} activeTask={activeTask} setActiveTask={setActiveTask} onTaskCompleted={handleTaskCompleted} recentTasks={tasks} onOpenQuickBuilder={()=>setIsQuickBuilderOpen(true)}/>} {activeTab==='agents'&&<AgentManager agents={agents} onSelectAgent={id=>{setSelectedAgentId(id);setActiveTab('assistant')}} onRefreshAgents={refreshAgents} onUsePrompt={()=>{}}/>} {activeTab==='files'&&<FileManager uploadedFiles={uploadedFiles} generatedArtifacts={allGeneratedArtifacts} onUploadFile={files=>{const u=[...files,...uploadedFiles];setUploadedFiles(u);localStorage.setItem('jarvis_uploaded_files',JSON.stringify(u));}} onDeleteUploadedFile={handleDeleteUploadedFile} onProcessFile={()=>setActiveTab('assistant')}/>} {activeTab==='memory'&&<MemoryManager memories={memories} onRefreshMemories={refreshMemories}/>} {activeTab==='history'&&<TaskHistory tasks={tasks} onOpenTask={t=>{setActiveTask(t);setActiveTab('assistant')}} onRepeatTask={t=>{setSelectedAgentId(t.agentId);setActiveTab('assistant')}} onDeleteTask={handleDeleteTask} onClearHistory={handleClearAllHistory}/>}<footer className="mt-8 mx-auto max-w-5xl w-full py-2.5 px-5 bg-white/5 border border-white/10 rounded-full flex flex-wrap items-center justify-between text-[11px] text-slate-400 gap-3"><div><span className="font-medium text-slate-300">● {isAiConfigured?'JARVIS AI Ready':'AI Configuration Required'}</span><span className="ml-4 text-cyan-300">● {agents.length} Autonomous Agents Ready</span></div><div className="font-mono"><span>Model: {settings.aiModel}</span><span className="ml-5">Memory: {memories.length} Grounded</span><span className="ml-5 text-cyan-400">v2.1.0</span></div></footer></main>
    <QuickExamBuilder isOpen={isQuickBuilderOpen} onClose={()=>setIsQuickBuilderOpen(false)} onSubmit={async(promptText,agentId)=>{setSelectedAgentId(agentId);setActiveTab('assistant');try{const task=await ApiService.executeTask({userPrompt:promptText,selectedAgentId:agentId,model:settings.aiModel,settings});setActiveTask(task);handleTaskCompleted(task);}catch(e){console.error(e);}}} settings={settings}/><SettingsModal isOpen={isSettingsOpen} onClose={()=>setIsSettingsOpen(false)} settings={settings} onSaveSettings={handleSaveSettings}/></div>;
}
