import React,{useEffect,useState} from 'react';
import {AgentDefinition,AttachedFile,JarvisMemoryItem,JarvisSettings,TaskRecord} from './types';
import {ApiService,DEFAULT_SETTINGS} from './services/api';
import {Header} from './components/Header';
import {OfficeAssistant} from './components/OfficeAssistant';
import {AgentManager} from './components/AgentManager';
import {FileManager} from './components/FileManager';
import {MemoryManager} from './components/MemoryManager';
import {TaskHistory} from './components/TaskHistory';
import {SettingsModal} from './components/SettingsModal';
import {QuickExamBuilder} from './components/QuickExamBuilder';
import {GlobalCommandBar} from './components/GlobalCommandBar';

export default function App(){
 const [activeTab,setActiveTab]=useState<'assistant'|'agents'|'files'|'memory'|'history'>('assistant');
 const [agents,setAgents]=useState<AgentDefinition[]>([]);const [selectedAgentId,setSelectedAgentId]=useState('auto');const [memories,setMemories]=useState<JarvisMemoryItem[]>([]);const [settings,setSettings]=useState<JarvisSettings>(DEFAULT_SETTINGS);const [tasks,setTasks]=useState<TaskRecord[]>([]);const [activeTask,setActiveTask]=useState<TaskRecord|null>(null);const [uploadedFiles,setUploadedFiles]=useState<AttachedFile[]>([]);const [isSettingsOpen,setIsSettingsOpen]=useState(false);const [isQuickBuilderOpen,setIsQuickBuilderOpen]=useState(false);const [isAiConfigured,setIsAiConfigured]=useState(false);
 useEffect(()=>{const init=async()=>{try{const ss=localStorage.getItem('jarvis_settings');if(ss)try{setSettings(JSON.parse(ss));}catch{}const st=localStorage.getItem('jarvis_task_history');if(st)try{setTasks(JSON.parse(st));}catch{}const sf=localStorage.getItem('jarvis_uploaded_files');if(sf)try{setUploadedFiles(JSON.parse(sf));}catch{}const [a,m,h]=await Promise.all([ApiService.getAgents(),ApiService.getMemories(),ApiService.checkHealth()]);setAgents(a);setMemories(m);setIsAiConfigured(Boolean(h?.aiConfigured));}catch(e){console.error(e);setIsAiConfigured(false);}};void init();},[]);
 const refreshAgents=async()=>{try{setAgents(await ApiService.getAgents());}catch(e){console.error(e);}};const refreshMemories=async()=>{try{setMemories(await ApiService.getMemories());}catch(e){console.error(e);}};
 const handleSaveSettings=(s:JarvisSettings)=>{setSettings(s);localStorage.setItem('jarvis_settings',JSON.stringify(s));};
 const handleTaskCompleted=(t:TaskRecord)=>{setTasks(p=>{const u=[t,...p.filter(x=>x.id!==t.id)].slice(0,50);localStorage.setItem('jarvis_task_history',JSON.stringify(u));return u;});if(t.attachedFiles?.length)setUploadedFiles(p=>{const map=new Map(p.map(f=>[f.id,f]));t.attachedFiles!.forEach(f=>map.set(f.id,f));const u=Array.from(map.values());localStorage.setItem('jarvis_uploaded_files',JSON.stringify(u));return u;});};
 const handleDeleteTask=(id:string)=>{setTasks(p=>{const u=p.filter(t=>t.id!==id);localStorage.setItem('jarvis_task_history',JSON.stringify(u));return u;});if(activeTask?.id===id)setActiveTask(null);};const handleClearAllHistory=()=>{setTasks([]);setActiveTask(null);localStorage.removeItem('jarvis_task_history');};const handleDeleteUploadedFile=(id:string)=>setUploadedFiles(p=>{const u=p.filter(f=>f.id!==id);localStorage.setItem('jarvis_uploaded_files',JSON.stringify(u));return u;});const allGeneratedArtifacts=tasks.flatMap(t=>(t.result?.artifacts||[]).map(artifact=>({artifact,taskTitle:t.title,date:t.completedAt||t.createdAt})));
 return <div className="jarvis-shell text-slate-200"><Header activeTab={activeTab} setActiveTab={setActiveTab} onOpenSettings={()=>setIsSettingsOpen(true)} onOpenQuickBuilder={()=>setIsQuickBuilderOpen(true)} isAiConfigured={isAiConfigured} settings={settings} taskCount={tasks.length}/><main className="jarvis-main"><div className="jarvis-content">{activeTab==='assistant'&&<OfficeAssistant agents={agents} selectedAgentId={selectedAgentId} setSelectedAgentId={setSelectedAgentId} settings={settings} activeTask={activeTask} setActiveTask={setActiveTask} onTaskCompleted={handleTaskCompleted} onAgentHired={refreshAgents} recentTasks={tasks}/>} {activeTab==='agents'&&<AgentManager agents={agents} onSelectAgent={id=>{setSelectedAgentId(id);setActiveTab('assistant')}} onRefreshAgents={refreshAgents} onUsePrompt={()=>{}}/>} {activeTab==='files'&&<FileManager uploadedFiles={uploadedFiles} generatedArtifacts={allGeneratedArtifacts} onUploadFile={files=>{const u=[...files,...uploadedFiles];setUploadedFiles(u);localStorage.setItem('jarvis_uploaded_files',JSON.stringify(u));}} onDeleteUploadedFile={handleDeleteUploadedFile} onProcessFile={()=>setActiveTab('assistant')}/>} {activeTab==='memory'&&<MemoryManager memories={memories} onRefreshMemories={refreshMemories}/>} {activeTab==='history'&&<TaskHistory tasks={tasks} onOpenTask={t=>{setActiveTask(t);setActiveTab('assistant')}} onRepeatTask={t=>{setSelectedAgentId(t.agentId);setActiveTab('assistant')}} onDeleteTask={handleDeleteTask} onClearHistory={handleClearAllHistory}/>}<footer className="mx-auto mt-8 flex w-full max-w-[1680px] flex-wrap items-center justify-between gap-3 px-1 py-3 text-[10px] text-slate-600"><div><span className={isAiConfigured?'text-emerald-400/70':'text-amber-400/70'}>● {isAiConfigured?'JARVIS online':'AI configuration required'}</span><span className="ml-4">{agents.length} employees</span></div><div>{settings.instituteName} · {settings.aiModel}</div></footer></div></main>{activeTab==='assistant'&&<GlobalCommandBar settings={settings} selectedAgentId={selectedAgentId} setActiveTask={setActiveTask} onTaskCompleted={handleTaskCompleted} onAgentHired={refreshAgents}/>}<QuickExamBuilder isOpen={isQuickBuilderOpen} onClose={()=>setIsQuickBuilderOpen(false)} onSubmit={async(promptText,agentId)=>{setSelectedAgentId(agentId);setActiveTab('assistant');try{const task=await ApiService.executeTask({userPrompt:promptText,selectedAgentId:agentId,model:settings.aiModel,settings});setActiveTask(task);handleTaskCompleted(task);}catch(e){console.error(e);}}} settings={settings}/><SettingsModal isOpen={isSettingsOpen} onClose={()=>setIsSettingsOpen(false)} settings={settings} onSave={handleSaveSettings}/></div>;
}
